# Generated by Django 3.2.7 on 2021-09-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_vendor', to='products.vendor', verbose_name='Vendor'),
        ),
    ]
